export const NUTRITIONIX_API = {
  APP_ID: process.env.EXPO_PUBLIC_NUTRITIONIX_APP_ID,
  API_KEY: process.env.EXPO_PUBLIC_NUTRITIONIX_API_KEY,
  BASE_URL: process.env.EXPO_PUBLIC_NUTRITIONIX_BASE_URL
};
